### ISSUE TITLE
OP TS snafu

### ISSUE THREAD

**Issue by The0x539** [butterfansubs/skelter-heaven#12]
84089e6d2c76236a80b233c20316c5f706d82c81

I vaguely understand the nature of this mistake, but not well enough to accurately describe what went wrong or how it should be fixed. A row has a clip tag where it shouldn't, but I'm not sure whether or not the sign is split at the appropriate timestamps.
![image](https://user-images.githubusercontent.com/7350294/78098864-dba45700-73a5-11ea-99a0-6232f8d1c4d9.png)

**Comment by Ristellise** [comment]
Fixed with one of the later commits.

**Comment by bucket3432** [comment]
Closed by commit 643af78fbcd8c0c602b9c51fc222aebfa5b5f4ea, to be precise.
