### ISSUE TITLE
Alt track - jymmy QC

### ISSUE THREAD

**Issue by jymmysmcsubs** [butterfansubs/skelter-heaven#8]
QC
timing for first couple of lines - this seems implausibly bad to me
"One Years After" sign... I find it difficult to believe they'd write this, to be honest
lines 43, 45 - add "~nari" to the end of the lines (omit terminal punctuation?) and double check for and additional ~nari lines

suggestions:
"go/going ahead" > "going first" (lines 88, 127, 226) this is less natural while being believable as a poor TL/editing choice
"time to recharge" > "It has quite a time lag." (line 98) - uses the English from the Japanese line
>{Am I hearing some Engrish in there that we have to keep literal? - Lann} - Yep
"entering into" > "directly entering into" (line 234) - feels in character to keep 直接

**Comment by Lann094** [comment]
> "One Years After" sign... I find it difficult to believe they'd write this, to be honest

I agree, I still prefer "One Year After"

> lines 43, 45 - add "~nari" to the end of the lines (omit terminal punctuation?) and double check for and additional ~nari lines

Not sure I'd expect to see this as a tic? Either way, I don't wanna have to listen to every line again, so I vote skip. :^)

> "go/going ahead" > "going first"

This was more the stock translation used for this phrase, in my eyes.

**Comment by bucket3432** [comment]
Reopening as not all feedback has been addressed.

**Comment by bucket3432** [comment]
Feedback has been addressed.
