### ISSUE TITLE
Unbalanced margins on two-liners

### ISSUE THREAD

**Issue by The0x539** [butterfansubs/skelter-heaven#9]
84089e6d2c76236a80b233c20316c5f706d82c81
![image](https://user-images.githubusercontent.com/7350294/78097930-456f3180-73a3-11ea-8f37-f2b46e1efe8d.png)
I dunno about you, but that don't look right to me.

**Comment by bucket3432** [comment]
I vote to keep. The vertical margin was calculated, and anything lower will cause the text to bleed into the overscan area.

**Comment by The0x539** [comment]
Overscan, schmoverscan. I don't get what the big deal with that is these days. It's not good to have stuff right up against the edge, no, but what's the actual ill effect?

**Comment by bucket3432** [comment]
It's perhaps not so relevant when you're watching on a computer screen, but some other devices might cut off the edges. I know my TV does, even if it has a flat panel display. The vertical margin is at 9 right now, but we can probably bring it down to 8 (for reference, completely even would be 6).
